Repository codedecks-in/LeetCode-Solutions, pull requests merged in 2021-10, with the labels that each got.

#201 Updated Readme for Swap Nodes in Pairs
  README.md
Labels: hacktoberfest-accepted

#196 20. Valid Parentheses
  Java/20.ValidParentheses.java
  README.md
Labels: hacktoberfest-accepted

#216 17. Letter Combinations of a Phone Number in C++
  C++/letter-combinations-of-a-phone-number.cpp
  README.md
Labels: hacktoberfest-accepted, hacktober-fest

#225 Single number js
  JavaScript/single-number.js
  README.md
Labels: hacktoberfest-accepted, hacktoberfest-2021, hacktober-fest

#205 Added solution for Spiral-matrix in cpp
  C++/Spiral-matrix.cpp
  README.md
Labels: hacktoberfest-accepted, hacktoberfest-2021, hacktoberfest, hacktober-fest

#217 Added solution for Jump game (55) using Dynamic Programming
  Python/jumpGame.py
  README.md
Labels: hacktoberfest-2021, hacktober-fest
